import ReviewOverviewView from '../features/posting/ReviewOverviewView.vue';
import type {ReviewOverviewContext} from '../features/posting/model.ts';
import {refreshToken as postingRefreshToken, clearRefresh as clearPostingRefresh} from '../features/posting/state.ts';
import ReviewDetailView from '../features/review/ReviewDetailView.vue';
import type {ReviewDetailContext} from '../features/review/guided-model.ts';
import DashboardView from '../features/overview/DashboardView.vue';
import AssetsView from '../features/overview/AssetsView.vue';
import TaxesView from '../features/overview/TaxesView.vue';
import type {OverviewContext} from '../features/overview/model.ts';
import TransactionListsView from '../features/transactions/TransactionListsView.vue';
import {buildIncomeCopy} from '../features/transactions/income-copy.ts';
import {copyable, type TransactionListContext} from '../features/transactions/model.ts';
import ContactsView from '../features/contacts/ContactsView.vue';
import type {ContactsContext} from '../features/contacts/model.ts';
import {mountView} from './host.ts';
import ExpenseDetail from '../features/expense-detail/ExpenseDetail.vue';
import type {ExpenseDetailContext} from '../features/expense-detail/model.ts';
const views = {postingRefreshToken, clearPostingRefresh, reviewOverview: (root: HTMLElement, context: ReviewOverviewContext) => mountView(root, ReviewOverviewView, context), reviewDetail: (root: HTMLElement, context: ReviewDetailContext) => mountView(root, ReviewDetailView, context), overview: (root: HTMLElement, context: OverviewContext) => mountView(root, {dashboard: DashboardView, assets: AssetsView, taxes: TaxesView}[context.view], context), buildIncomeCopy, copyable, transactions: (root: HTMLElement, context: TransactionListContext) => mountView(root, TransactionListsView, context), contacts: (root: HTMLElement, context: ContactsContext) => mountView(root, ContactsView, context), expenseDetail: (root: HTMLElement, context: ExpenseDetailContext) => mountView(root, ExpenseDetail, context)};
declare global {var AutonomoViews: typeof views;}
globalThis.AutonomoViews = views;
