import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {JSDOM} from 'jsdom';
import {expect, test} from 'vitest';
import {legacyCore} from '../src/core/legacy.ts';

test('legacy fragment replacement releases records and preserves live help history', async () => {
  const dom = new JSDOM('<body><div id="rows"></div><div id="sibling"></div><dialog id="status-help-dialog"><h2 id="status-help-title"></h2><div id="status-help-body"></div><button id="status-help-close"></button></dialog></body>', {url: 'https://example.invalid/income', runScripts: 'outside-only'});
  const context = dom.getInternalVMContext();
  const maps: Map<unknown, unknown>[] = [];
  context.Map = class extends Map {constructor() {super(); maps.push(this);}};
  context.AutonomoCore = legacyCore;
  context.scrollTo = () => {};
  const dialog = dom.window.document.querySelector('dialog')!;
  dialog.showModal = () => {dialog.open = true;};
  dialog.close = () => {dialog.open = false;};
  vm.runInContext(readFileSync('src/autonomo_taxes/web_ui/status-help.js', 'utf8'), context);
  const help = context.AccountingHelp;
  const rows = dom.window.document.querySelector('#rows')!;
  const sibling = dom.window.document.querySelector('#sibling')!;
  const oldRecord = {domain: 'transaction', state: 'ready', title: 'Discarded record'};
  rows.innerHTML = help.cell(oldRecord);
  sibling.innerHTML = help.cell({domain: 'transaction', state: 'ready', title: 'Live record'});
  const staleId = rows.querySelector('button')!.dataset.statusHelp;
  const liveId = sibling.querySelector('button')!.dataset.statusHelp;
  await Promise.resolve();
  rows.innerHTML = '';
  await Promise.resolve();
  expect(maps[0]!.has(staleId)).toBe(false);
  expect(maps[0]!.has(liveId)).toBe(true);
  sibling.querySelector('button')!.click();
  expect(dialog.open).toBe(true);
  expect(dom.window.document.querySelector('#status-help-title')!.textContent).toBe('Live record');
  dom.window.addEventListener('popstate', () => help.handlePopState());
  const navigate = (direction: 'back' | 'forward') => new Promise<void>(resolve => {
    dom.window.addEventListener('popstate', () => resolve(), {once: true});
    dom.window.history[direction]();
  });
  await navigate('back');
  expect(dialog.open).toBe(false);
  await navigate('forward');
  expect(dialog.open).toBe(true);
  sibling.innerHTML = '';
  await Promise.resolve();
  expect(maps[0]!.has(liveId)).toBe(true);
  await navigate('back');
  expect(maps[0]!.has(liveId)).toBe(false);
  help.beforeRender();
  dom.window.history.replaceState({accountingHelp: staleId}, '');
  expect(help.handlePopState()).toBe(false);
  expect(dialog.open).toBe(false);
  const first = help.createScope({domain: 'transaction', state: 'ready'});
  const second = help.createScope({domain: 'transaction', state: 'blocked'});
  rows.innerHTML = '<span>Unrelated partial render</span>';
  await Promise.resolve();
  expect(maps[0]!.has(first.id)).toBe(true);
  first.update({domain: 'transaction', state: 'posted'});
  expect(maps[0]!.get(first.id)).toMatchObject({state: 'posted'});
  first.dispose(); first.dispose();
  expect(maps[0]!.has(first.id)).toBe(false);
  expect(maps[0]!.has(second.id)).toBe(true);
  second.dispose();
  dom.window.close();
});
