"""Reusable synthetic fixtures shared by backend test suites."""

from __future__ import annotations
import csv
from decimal import Decimal
import json
from pathlib import Path
import pytest
from autonomo_taxes.cli import main
from autonomo_taxes.counterparty_names import CounterpartyMatchError
from autonomo_taxes.filing_evidence import FilingEvidence
from autonomo_taxes.history_migration import (
    _find_acquisition_transaction,
    _prune_unreferenced_migration_counterparty,
    _prune_superseded_source_book_records,
    _tax_code_for_row,
    _upsert_counterparty,
    _usable_tax_id,
    migrate_xolo_history,
    refresh_filing_inventory,
)
from autonomo_taxes.ledger_db import BlockingIssueError, ClosedPeriodError, LedgerDB
SOURCE_BOOK_FIELDS = [
    "source_book_type",
    "source_scope",
    "source_file",
    "source_file_format",
    "source_row_number",
    "source_book_line_id",
    "period",
    "date",
    "booking_date",
    "supplier",
    "document_number",
    "counterparty_country_code",
    "counterparty_tax_id",
    "counterparty_vat_id",
    "invoice_type",
    "operation_key",
    "operation_qualification",
    "exempt_operation",
    "reverse_charge",
    "original_amount",
    "original_currency",
    "gross_eur",
    "invoice_total_eur",
    "taxable_base_eur",
    "vat_rate_percent",
    "vat_eur",
    "deductible_vat_eur",
    "withholding_rate_percent",
    "withholding_eur",
    "deductible_base_eur",
    "irpf_deductible_eur",
    "vat_treatment",
    "reason_code",
    "asset_id",
    "amortizable_base_eur",
    "amortization_period",
    "amortization_amount_eur",
    "rate_or_life",
    "casilla01_ytd",
    "casilla02_ytd",
    "casilla07",
    "casilla19",
    "import_status",
    "missing_required_groups",
    "notes",
]
RECONCILIATION_FIELDS = [
    "status",
    "date",
    "recipient",
    "number",
    "currency",
    "amount_original",
    "gross_eur",
    "irpf_deductible_eur",
    "local_deductible_eur",
    "deductible_diff_eur",
    "local_document",
    "xolo_id",
    "notes",
]

SOURCE_BOOK_FIELDS = [
    "source_book_type",
    "source_scope",
    "source_file",
    "source_file_format",
    "source_row_number",
    "source_book_line_id",
    "period",
    "date",
    "booking_date",
    "supplier",
    "document_number",
    "counterparty_country_code",
    "counterparty_tax_id",
    "counterparty_vat_id",
    "invoice_type",
    "operation_key",
    "operation_qualification",
    "exempt_operation",
    "reverse_charge",
    "original_amount",
    "original_currency",
    "gross_eur",
    "invoice_total_eur",
    "taxable_base_eur",
    "vat_rate_percent",
    "vat_eur",
    "deductible_vat_eur",
    "withholding_rate_percent",
    "withholding_eur",
    "deductible_base_eur",
    "irpf_deductible_eur",
    "vat_treatment",
    "reason_code",
    "asset_id",
    "amortizable_base_eur",
    "amortization_period",
    "amortization_amount_eur",
    "rate_or_life",
    "casilla01_ytd",
    "casilla02_ytd",
    "casilla07",
    "casilla19",
    "import_status",
    "missing_required_groups",
    "notes",
]

RECONCILIATION_FIELDS = [
    "status",
    "date",
    "recipient",
    "number",
    "currency",
    "amount_original",
    "gross_eur",
    "irpf_deductible_eur",
    "local_deductible_eur",
    "deductible_diff_eur",
    "local_document",
    "xolo_id",
    "notes",
]

def _write_fixture_csvs(tmp_path: Path) -> tuple[Path, Path]:
    source_csv = tmp_path / "runs" / "xolo_source_book_rows.csv"
    reconciliation_csv = tmp_path / "runs" / "2026-Q2" / "xolo_expense_reconcile.csv"

    _write_csv(
        source_csv,
        SOURCE_BOOK_FIELDS,
        [
            {
                "source_book_type": "ingresos_book",
                "source_scope": "2026",
                "source_file": str(tmp_path / "evidence" / "income.xlsx"),
                "source_file_format": "xlsx:sheet1:r6-r7",
                "source_row_number": "2",
                "source_book_line_id": "income-line-1",
                "period": "2026-Q2",
                "date": "15/04/2026",
                "booking_date": "",
                "supplier": "Example Customer One",
                "document_number": "INV-2026-001",
                "original_amount": "",
                "original_currency": "",
                "gross_eur": "1500.00",
                "deductible_base_eur": "",
                "irpf_deductible_eur": "",
                "vat_treatment": "",
                "reason_code": "I01",
                "asset_id": "",
                "amortizable_base_eur": "",
                "amortization_period": "",
                "amortization_amount_eur": "",
                "rate_or_life": "",
                "casilla01_ytd": "",
                "casilla02_ytd": "",
                "casilla07": "",
                "casilla19": "",
                "import_status": "imported",
                "missing_required_groups": "",
                "notes": "",
            },
            {
                "source_book_type": "gastos_book",
                "source_scope": "2026",
                "source_file": str(tmp_path / "evidence" / "expense.xlsx"),
                "source_file_format": "xlsx:sheet2:r6-r7",
                "source_row_number": "3",
                "source_book_line_id": "expense-line-1",
                "period": "2026-Q2",
                "date": "21/04/2024",
                "booking_date": "22/04/2024",
                "supplier": "Cursor",
                "document_number": "204355514",
                "original_amount": "24,20",
                "original_currency": "USD",
                "gross_eur": "20,73",
                "deductible_base_eur": "17,14",
                "irpf_deductible_eur": "17,14",
                "vat_treatment": "",
                "reason_code": "G03",
                "asset_id": "",
                "amortizable_base_eur": "",
                "amortization_period": "",
                "amortization_amount_eur": "",
                "rate_or_life": "",
                "casilla01_ytd": "",
                "casilla02_ytd": "",
                "casilla07": "",
                "casilla19": "",
                "import_status": "imported",
                "missing_required_groups": "",
                "notes": "Historical expense import",
            },
            {
                "source_book_type": "bienes_inversion_book",
                "source_scope": "2026",
                "source_file": str(tmp_path / "evidence" / "assets.xlsx"),
                "source_file_format": "xlsx:sheet3:r6-r7",
                "source_row_number": "4",
                "source_book_line_id": "asset-line-1",
                "period": "",
                "date": "08/04/2026",
                "booking_date": "",
                "supplier": "Synthetic Party 016",
                "document_number": "",
                "original_amount": "",
                "original_currency": "",
                "gross_eur": "",
                "deductible_base_eur": "",
                "irpf_deductible_eur": "",
                "vat_treatment": "",
                "reason_code": "",
                "asset_id": "MacBook Pro 14",
                "amortizable_base_eur": "1647.93",
                "amortization_period": "0A",
                "amortization_amount_eur": "313.12",
                "rate_or_life": "26%",
                "casilla01_ytd": "",
                "casilla02_ytd": "",
                "casilla07": "",
                "casilla19": "",
                "import_status": "imported",
                "missing_required_groups": "",
                "notes": "Annual asset evidence only",
            },
        ],
    )

    _write_csv(
        reconciliation_csv,
        RECONCILIATION_FIELDS,
        [
            {
                "status": "amount_mismatch",
                "date": "2026-05-01",
                "recipient": "Cursor",
                "number": "204355514",
                "currency": "USD",
                "amount_original": "24,20",
                "gross_eur": "20,73",
                "irpf_deductible_eur": "20,73",
                "local_deductible_eur": "17,14",
                "deductible_diff_eur": "3,59",
                "local_document": "Invoice-204355514.pdf",
                "xolo_id": "2918422",
                "notes": "Difference still unresolved",
            },
            {
                "status": "deductibility_pending_confirmation",
                "date": "2026-06-10",
                "recipient": "Synthetic Party 011",
                "number": "SYNTH-DOCUMENT-018",
                "currency": "EUR",
                "amount_original": "104,33",
                "gross_eur": "104,33",
                "irpf_deductible_eur": "104,33",
                "local_deductible_eur": "",
                "deductible_diff_eur": "",
                "local_document": "03_Apremio_08-2024_104.33EUR.pdf",
                "xolo_id": "3099343",
                "notes": "Needs tax treatment confirmation",
            },
            {
                "status": "missing_locally",
                "date": "2026-06-30",
                "recipient": "Synthetic Party 002",
                "number": "SYNTH-DOCUMENT-030",
                "currency": "USD",
                "amount_original": "75,98",
                "gross_eur": "65,10",
                "irpf_deductible_eur": "65,10",
                "local_deductible_eur": "",
                "deductible_diff_eur": "",
                "local_document": "",
                "xolo_id": "3141770",
                "notes": "Missing in local archive",
            },
            {
                "status": "matched_local",
                "date": "2026-04-24",
                "recipient": "Synthetic Party 007",
                "number": "00012",
                "currency": "EUR",
                "amount_original": "18,00",
                "gross_eur": "18,00",
                "irpf_deductible_eur": "18,00",
                "local_deductible_eur": "18,00",
                "deductible_diff_eur": "0,00",
                "local_document": "Invoice-00012.pdf",
                "xolo_id": "2887712",
                "notes": "",
            },
        ],
    )

    return source_csv, reconciliation_csv

def _write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

def _load_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))
